# Visualization

In [88]:
import numpy as np
import networkx as nx
from pyvis.network import Network
from IPython.core.display import display, HTML
import matplotlib.pyplot as plt
import pandas as pd
import webbrowser
import os

In [89]:
class GraphVisualizer:
    # Stores the input dataframe list.
    def __init__(self, dataframe_list):
        self.dataframe_list = dataframe_list

    # Converts each dataframe to a networkx graph.
    def create_graphs(self):
        self.graph_list = [nx.from_pandas_adjacency(df) for df in self.dataframe_list]
        return self.graph_list

    # Converts each graph into a pyvis network and visualizes it as an HTML file.
    def visualize_graphs(self):
        for i, G in enumerate(self.graph_list):
            for u, v, data in G.edges(data=True):
                data['title'] = str(data.get('weight', ''))
            net = Network(notebook=True, cdn_resources='remote')
            net.from_nx(G)
            filename = "graph" + str(i) + ".html"
            net.show(filename)  # Saves it as an HTML file.
            webbrowser.open('file://' + os.path.realpath(filename))  # Opens the HTML file in a web browser.

In [90]:
IGO_df = pd.read_csv("IGO_adjmat_scaled_topXpct_important.csv", index_col=0)
DCAD_df = pd.read_csv("DCAD_adjmat_top5pct.csv", index_col=0)

In [91]:
IGO_df

,KOR,FRN,RUS,JPN,GER,CHN,UKG,USA,AUL,IND
KOR,0.000000,0.677083,0.645833,0.739583,0.677083,0.677083,0.000000,0.708333,0.645833,0.645833
FRN,0.677083,0.000000,0.645833,0.739583,0.854167,0.000000,0.812500,0.802083,0.000000,0.000000
RUS,0.645833,0.645833,0.000000,0.000000,0.000000,0.000000,0.000000,0.656250,0.000000,0.000000
JPN,0.739583,0.739583,0.000000,0.000000,0.750000,0.000000,0.739583,0.802083,0.687500,0.645833
GER,0.677083,0.854167,0.000000,0.750000,0.000000,0.000000,0.833333,0.760417,0.000000,0.000000
CHN,0.677083,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667
UKG,0.000000,0.812500,0.000000,0.739583,0.833333,0.000000,0.000000,0.781250,0.000000,0.000000
USA,0.708333,0.802083,0.656250,0.802083,0.760417,0.000000,0.781250,0.000000,0.677083,0.000000
AUL,0.645833,0.000000,0.000000,0.687500,0.000000,0.000000,0.000000,0.677083,0.000000,0.000000
IND,0.645833,0.000000,0.000000,0.645833,0.000000,0.666667,0.000000,0.000000,0.000000,0.000000

In [92]:
DCAD_df

     BRA  BUL  CHN  IND  RUS  SAF  SPN  TUR  UKR  USA
BRA  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
BUL  0.0  0.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0
CHN  1.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0
IND  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0
RUS  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
SAF  1.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
SPN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
TUR  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
UKR  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0
USA  1.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0

In [93]:
my_visualizer = GraphVisualizer([IGO_df, DCAD_df])
my_visualizer.create_graphs()
my_visualizer.visualize_graphs()

graph0.html
graph1.html